#!/usr/bin/env zsh

printf "Create absolute symbolic links in home directory."

mkdir -p ~/.config/fd
mkdir -p ~/.config/ghostty
mkdir -p ~/.config/git
mkdir -p ~/.config/nvim
mkdir -p ~/.config/tmux

mkdir -p ~/.docker
mkdir -p ~/.gnupg
mkdir -p ~/.ssh


ln -sfn $(pwd)/dot-zshrc ~/.zshrc

ln -sfn $(pwd)/dot-config/fd/* ~/.config/fd/
ln -sfn $(pwd)/dot-config/ghostty/* ~/.config/ghostty/
ln -sfn $(pwd)/dot-config/git/* ~/.config/git/
ln -sfn $(pwd)/dot-config/nvim/* ~/.config/nvim/
ln -sfn $(pwd)/dot-config/tmux/* ~/.config/tmux/

ln -sfn $(pwd)/dot-docker/* ~/.docker/
ln -sfn $(pwd)/dot-gnupg/* ~/.gnupg/
ln -sfn $(pwd)/dot-ssh/* ~/.ssh/
